#germanTranslation
#indexPage is the landingPage its actually a startMenu
indexPage:
  - license: Lizenz
  - imprint: Impressum und Datenschutz
  - changeTheme: Ã„ndere Farbschema
  - moreOptions: Mehr Optionen